NAME ={
    "Bui Viet Hoang" :"Bùi Việt Hoàng",
    "Chu Trong Doan" :"Chu Trọng Đoàn",
    "Dang Danh Viet" :"Đặng Danh Việt",
    "Dang Ngoc Thai" : "Sếp Thái",
    "Dang Van Nam" :"Đăng Văn Nam ",
    "Doan Thi Giang":"Đoàn Thị Giang",
    "Hoang Thu Anh" :"Hoàng Thu Anh",
    "Luu Thi Phuong" :"Lưu Thị Phượng",
    "Nguyen Hue Diep" :"Nguyễn Huệ Điệp",
    "Nguyen Hung Cuong": "Nguyễn Hùng Cường",
    "Nguyen Phuc Toan" : "Nguyễn Phúc Toàn ",
    "Nguyen Quoc Hieu" :"Nguyễn Quốc Hiếu ",
    "Nguyen Thanh Tuyen":"Nguyễn Thanh Tuyển ",
    "Nguyen Tien Anh " :"Nguyễn Tiến Anh ",
    "Nguyen Van Hoang" : "Nguyễn Văn Hoàng",
    "Nguyen Van Minh" : "Nguyên Văn Minh",
    "Nguyen Viet Anh" :" Việt Anh NG",
    "Nguyen Xuan Hoai" :"Thầy Hoài",
    "Pham Thuy Tien" :"Phạm Thủy Tiên",
    "Pham Viet Dung" :"Phạm Việt Dũng",
    "Phan Thi Hai Hong" :"Cô Hồng",
    "Tran Dinh Manh Cuong":"Trần Cường",
    "Tran Thuy Hao" :"Trần Thúy Hảo",
    "Trinh Dinh Hoa" :"Trịnh Đình Hòa",
    "Truong Thi Le" :"Lệ",
    "Vu Tien Hung" : " Hùng"
}